# .scrutinizer.yml

build:
    environment:
        sdkman:
            - gradle@4.2.1
    tests:
        override:
            - gradle test
checks:
    java: true
    filter:
        excluded_paths:
            - test/*